// Alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const USER_NOT_LOADED = "USER_NOT_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// Item
export const GET_ALL_ITEMS = "GET_ALL_ITEMS";
export const ITEMS_ERROR = "ITEMS_ERROR";
export const GET_TYPE_ITEMS = "GET_TYPE_ITEMS";
export const GET_ITEM = "GET_ITEM";

// My-Cart
export const ADD_TO_MYCART = "ADD_TO_MYCART";
export const MYCART_ERROR = "MYCART_ERROR";
export const GET_MYCART_ITEMS = "GET_MYCART_ITEMS";
export const DELETE_ITEM = "DELETE_ITEM";
export const CHANGE_ITEM_QUANTITY = "CHANGE_ITEM_QUANTITY";
export const CLEAR_MYCART = "CLEAR_MYCART";

// Delivery
export const GET_DELIVERY_INFO = "GET_DELIVERY_INFO";
export const DELIVERY_ERROR = "DELIVERY_ERROR";
export const ADD_OR_UPDATE_DELIVERY_INFO = "ADD_OR_UPDATE_DELIVERY_INFO";

// Payment
export const GET_PAYMENT_INFO = "GET_PAYMENT_INFO";
export const PAYMENT_ERROR = "PAYMENT_ERROR";
export const ADD_OR_UPDATE_PAYMENT_INFO = "ADD_OR_UPDATE_PAYMENT_INFO";

// Order
export const COMPLETE_ORDER = "COMPLETE_ORDER";
export const ORDER_ERROR = "ORDER_ERROR";
export const CONFIRMATION_EMAIL_SENT ="CONFIRMATION_EMAIL_SENT";
export const EMAIL_ERROR = "EMAIL_ERROR";